<script setup lang="ts">
import {
  LayoutDashboard,
  History,
  Calculator,
  Settings2,
  ArrowUpRight,
  ArrowDownRight,
  ChevronRight,
  ChevronLeft,
  ChevronsRight,
  Plus,
  Search,
  X,
  Check,
  Clock3,
  RotateCcw,
  LogOut,
  LockKeyhole,
  TrendingUp,
  ArrowRight,
  ChartNoAxesCombined,
  CalendarDays,
  SlidersHorizontal,
  CircleHelp,
  Trophy,
  Circle,
  Flag,
  Menu,
  LoaderCircle,
  Pencil,
  Trash2,
} from '@lucide/vue'
const props = withDefaults(defineProps<{ name: string; size?: number }>(), { size: 20 })
const icons = {
  overview: LayoutDashboard,
  archive: History,
  simulator: Calculator,
  settings: Settings2,
  up: ArrowUpRight,
  down: ArrowDownRight,
  right: ChevronRight,
  left: ChevronLeft,
  boost: ChevronsRight,
  plus: Plus,
  search: Search,
  close: X,
  check: Check,
  pending: Clock3,
  restore: RotateCcw,
  logout: LogOut,
  lock: LockKeyhole,
  trend: TrendingUp,
  arrow: ArrowRight,
  chart: ChartNoAxesCombined,
  calendar: CalendarDays,
  filter: SlidersHorizontal,
  help: CircleHelp,
  trophy: Trophy,
  ball: Circle,
  flag: Flag,
  menu: Menu,
  loading: LoaderCircle,
  edit: Pencil,
  trash: Trash2,
}
const icon = computed(() => icons[props.name as keyof typeof icons] ?? Circle)
</script>
<template><component :is="icon" :size="size" :stroke-width="1.7" aria-hidden="true" /></template>
